### ISSUE TITLE
дополнение к мошенничеству

### ISSUE THREAD

**Issue by bringmetheaugust** [VSerj/Type-faster#13]
надо еще запретить пользователю выделять вводимый текст, так как его до сих пор можно скопировать: выделить текст мышкой, правой кнопкой открыть дополнительное меню и нажать **копировать**.

запретить возможность выделять текст лучше и проще всего с помощью `CSS`

**Comment by VSerj** [comment]
думал об этом. 
ок - установлю запрет.

**Comment by VSerj** [comment]
готово
