### ISSUE TITLE
неудобная кнопка ночной темы

### ISSUE THREAD

**Issue by bringmetheaugust** [VSerj/Type-faster#19]
местонахождения кнопки ночной темы неудобное.
её надо поместить в том же месте, где и кнопка статистики

**Comment by VSerj** [comment]
Действительно, неудобно.

Изначально избегал слипания элементов (для мобильных версий). Добавил скрин.
![image](https://user-images.githubusercontent.com/44513805/102922698-2071a000-4497-11eb-8be8-1495083be67e.png)

Может сделать медиазапрос, для небольшой ширины экрана, оставить в правом верхнем, а далее возле статистики? Это непростое UX решение.

**Comment by bringmetheaugust** [comment]
давай тогда для моб версии пусть будет как у тебя на скрине.
а на десктопе поместить кнопку тёмной темы возле кнопки статистики

**Comment by VSerj** [comment]
![image](https://user-images.githubusercontent.com/44513805/103010547-2fad2800-4541-11eb-864e-784ee2cf4c80.png)
Для мобильной еще можно как на скрине

**Comment by bringmetheaugust** [comment]
> Для мобильной еще можно как на скрине. Как думаешь?

думаю, что нет.
лого сайта лучше всего здесь бы смотрелось по центру (как раньше), а кнопки симметрично по бокам от этого лого

**Comment by VSerj** [comment]
Пока оставим так.
