### ISSUE TITLE
доработать тёмную тему

### ISSUE THREAD

**Issue by bringmetheaugust** [VSerj/Type-faster#21]
при активированной тёмной темы плохо воспринимаются кнопки **Start** и выбор время набора (радиобаттоны), потому что у них тускло-зелёный цвет.
надо подобрать ярче цвет (не обязательно зелёный), чтобы их было лучше видно

**Comment by VSerj** [comment]
Тоже думал, выбрал этот вариант.
Не хотел пользователя отвлекать яркими кнопками на общем фоне, при наборе текста.
Поищу еще цвета
