### ISSUE TITLE
нет прелоадера во время запроса на API

### ISSUE THREAD

**Issue by bringmetheaugust** [VSerj/Type-faster#7]
время ответа **API** может быть любое (например, до 10 секунд).
этот показатель зависит как и от нагружености сервера с **API**, так и со скоростью интернета у юзера.

нужно во время начала запроса показывать прелоадер (или показывать текстово аля _"подождите, текст загружается"_, чтобы юзер видел, что загрузка идет.

самая наглядная ситуация:
сервер **API** загружен и его средняя скорость ответа на запрос равна 10секундам.
юзер зашел на тренажер. нажал старт, а текста нет. спустя 5 секунд он снова будет жать **start**, так как не понимает, почему ничего не происходит. в итоге он решит, что ничего не работает и просто уйдет

**Comment by VSerj** [comment]
Спасибо за замечание. Добавил прелоадер-заглушку в целях информирования пользователя.3a7348894d2bdde1c4b2043148b0874905fcedfc

**Comment by bringmetheaugust** [comment]
ну по **UI** получилось так себе, но цель достигнута
